### ISSUE TITLE
Line mismatch in error message

### ISSUE THREAD

**Issue by hugovk** [sphinx-contrib/sphinx-lint#32]
sphinx-lint==0.6 finds a valid bug in this file:

https://github.com/python-pillow/Pillow/blame/a50addb8e212e57dfe703b3d792691b3e18b2587/winbuild/build.rst#L45

```
winbuild/build.rst:44: inline literal missing (escaped) space after literal: '``ARM64``b' (missing-space-after-literal)
```

However, the problem is on line 45 not 44.

**Comment by ezio-melotti** [comment]
This seems caused a bug in the `paragraph` function:
https://github.com/sphinx-contrib/sphinx-lint/blob/b3775563717e4c875cabd0e6709c47094a8d0bfa/sphinxlint.py#L239-L253

I tried to run it on the file you linked, and it produced these numbers:
```pycon
>>> with open(fname) as f:
...   for lno, p in paragraphs(f.readlines()):
...     print(lno, repr(p[:30]))
... 
1 'Building Pillow on Windows\n==='
3 '.. note:: For most people, the'
7 'This page describes the steps '
10 'Prerequisites\n-------------\n'
13 'Compilers\n^^^^^^^^^\n'
17 'Download and install:\n'
19 '* `Microsoft Visual Studio 201'
23 '* `CMake 3.12 or newer <https:'
26 '* x86/x64: `NASM <https://www.'
28 'Any version of Visual Studio 2'
31 'Paths to CMake (if standalone)'
34 'Build configuration\n----------'
37 'The following environment vari'
40 '* ``PYTHON`` + ``EXECUTABLE`` '
53 '``build_prepare.py`` also supp'
55 '* ``-v`` will print generated '
```

The relevant paragraph here is the one that starts with `* ``PYTHON`` + ``EXECUTABLE`` `.  The `paragraphs` function says it starts at line `40`, however the correct line number should be `41`.  Some of the other values are also off.

The following bit of code in `check_missing_space_after_literal` does `40 + 4` and gets `44`, instead of doing `41 + 4` and get `45`.
https://github.com/sphinx-contrib/sphinx-lint/blob/b3775563717e4c875cabd0e6709c47094a8d0bfa/sphinxlint.py#L230-L236

**Comment by JulienPalard** [comment]
I'm releasing v0.6.1 to fix this, thanks for reporting @hugovk! (And for fixing @ezio-melotti!)
